client/urls.py
from django.urls import path

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients, name='index'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete', views.clients_delete, name='delete'),
    path('<int:pk>/edit', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_add_file, name='add_file'),
    path('add-client', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
]

crm_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('login/', views.LoginView.as_view(template_name='userprofile/login.html',
         authentication_form=LoginForm), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='index'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.LeadsExportView.as_view(), name='export'),
]

client/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(
        Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='client', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class ClientFile(models.Model):
    team = models.ForeignKey(
        Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(
        Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(
        User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username


class Comment(models.Model):
    team = models.ForeignKey(
        Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(
        Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

client/forms.py
from django import forms
from .models import Client, Comment, ClientFile


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description')


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file',)

client/views.py
import csv

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import Client
from .forms import AddClientForm, AddCommentForm, AddFileForm

from team.models import Team


@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(["Client", "Email", "Description",
                    "Created_at", "Created_by"])

    for client in clients:
        writer.writerow([client.name, client.email, client.description,
                        client.created_at, client.created_by])

    return response


@login_required
def clients(request):
    clients = Client.objects.filter(created_by=request.user)
    return render(request, 'client/clients.html', {
        'clients': clients,
    })


@login_required
def clients_add_file(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    # team = Team.objects.filter(created_by=request.user)[0]

    if request.method == 'POST':
        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.created_by = request.user
            file.client_id = pk
            file.save()

            return redirect('clients:detail', pk=pk)

    return redirect('clients:detail', pk=pk)


@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.client = client
            comment.save()

            return redirect('clients:detail', pk=pk)

    else:
        form = AddCommentForm()

    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form': form,
        'fileform': AddFileForm(),
    })


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    if request.method == "POST":
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

        messages.success(request, 'Changes were saved')
        return redirect('clients:index')
    else:
        form = AddClientForm(instance=client)

    return render(request, 'client/clients_edit.html', {
        'form': form,
    })


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, 'The client was deleted')

    return redirect('clients:index')


@login_required
def clients_add(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST)

        if form.is_valid():
            client = form.save(commit=False)
            client.created_by = request.user
            client.team = request.user.userprofile.active_team
            client.save()

            messages.success(request, 'The client was created')

            return redirect('clients:index')

    else:
        form = AddClientForm()

    return render(request, 'client/clients_add.html', {
        'form': form,
        'team': request.user.userprofile.active_team,
    })

client/templates/client/clients.html
{% extends 'core/base.html' %}

{% block title %}Clients{% endblock %}

{% block content %}
    <h1 class="mb-4 text-xl">Clients</h1>
    <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 text-white rounded-xl">Add client</a>
    <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white">Export clients</a>

    {% if clients %}
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        </div>
        {% for client in clients %}
            <div class="flex justify-between">
                <p class="py-4 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
                </p>
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-6 px-2">There are no clients in the database yet.</p>
    {% endif %}
{% endblock %}

client/templates/client/clients_add.html
{% extends 'core/base.html' %}

{% block title %}Add client{% endblock %}

{% block content %}
    <h1 class="text-xl">Add client</h1>
    {% if team.plan.max_clients > team.clients.all|length %}
        <form method="post" action="">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </form>
    {% else %}
        <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
            Your team has reached maximum number of clients. Your owner must upgrade your plan!
        </div>
    {% endif %}
{% endblock %}

client/templates/client/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <h1 class="mb-4 text-xl">{{ client.name }}</h1>

    {% if client.description %}
        <p class="font-semibold">name</p>
        <p class="mb-2">{{ client.description }}</p>
    {% endif %}

    <p class="font-semibold">Created at</p>
    <p class="mb-2">{{ client.created_at }}</p>

    <p class="font-semibold">Modified at</p>
    <p class="mb-6">{{ client.modified_at }}</p>

    <hr class="my-4">
        <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl text-white bg-blue-500">Edit</a>
        <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl text-white bg-red-500">Delete</a>
    <hr class="my-4">

    <h2 class="mb-6 text-xl">Comments</h2>

    <div>
        {% for comment in client.comments.all %}
        <div class="mb-4 bg-gray-100 px-6 py-6 rounded-xl">
            <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{comment.created_at }}</p>
            {{ comment.content }}
        </div>
        {% endfor %}
    </div>

    <form method="post" action="{% url 'clients:add_comment' client.id %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-2 px-4 rounded-xl text-white bg-teal-500">Submit</button>
    </form>


    <hr class="my-4">

    <h2 class="mb-6 text-xl">Files</h2>

    <div>
        {% for file in client.files.all %}
        <div class="mb-4 bg-gray-100 px-6 py-6 rounded-xl">
            <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{file.created_at }}</p>
            <a href="{{ file.file.url }}">Download</a>
        </div>
        {% endfor %}
    </div>


    <form method="post" action="{% url 'clients:add_file' client.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{ fileform.as_p }}

        <button class="mt-4 py-2 px-4 rounded-xl text-white bg-teal-500">Upload</button>
    </form> 


    <hr class="my-4">

    <a href="{% url 'clients:index' %}">Back to clients</a>

{% endblock %}

client/templates/client/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit client{% endblock %}

{% block content %}
    <h1 class="text-xl">Edit client</h1>
    <form method="post" action="">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>

{% endblock %}