crm_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('login/', views.LoginView.as_view(template_name='userprofile/login.html',
         authentication_form=LoginForm), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/urls.py
from django.urls import path
from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='index'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add/', views.LeadCreateView.as_view(), name='add'),
    path('export/', views.LeadsExportView.as_view(), name='export'),
]

lead/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(
        Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(
        max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(
        max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class LeadFile(models.Model):
    team = models.ForeignKey(
        Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(
        Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(
        User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username


class Comment(models.Model):
    team = models.ForeignKey(
        Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(
        Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

lead/forms.py
from django import forms
from .models import Lead, Comment, LeadFile


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file',)

lead/views.py
import csv

from typing import Any, Dict
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.db.models.query import QuerySet
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from django.views import View

from .forms import AddCommentForm, AddFileForm
from .models import Lead

from client.models import Client, Comment as ClientComment

from team.models import Team


class LeadsExportView(LoginRequiredMixin, View):

    class Meta:
        model = Lead

    def get(self, *args, **kwargs):
        leads = Lead.objects.filter(created_by=self.request.user)
        response = HttpResponse(
            content_type="text/csv",
            headers={"Content-Disposition": 'attachment; filename="leads.csv"'},
        )

        writer = csv.writer(response)
        writer.writerow(["Lead", "Email", "Description",
                         "Priority", "Status", "Converted_to_client",
                        "Created_at", "Created_by"])

        for lead in leads:
            writer.writerow([lead.name, lead.email, lead.description,
                             lead.priority, lead.status, lead.converted_to_client,
                            lead.created_at, lead.created_by])

        return response


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super(LeadListView, self).get_queryset()
        return queryset.filter(
            created_by=self.request.user, converted_to_client=False)


class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()
        context['fileform'] = AddFileForm()
        return context

    def get_object(self):
        obj = super().get_object()
        return obj


class LeadDeleteView(LoginRequiredMixin, DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:index')


class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ['name', 'email', 'description', 'priority', 'status']
    success_url = reverse_lazy('leads:index')

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['team'] = self.request.user.userprofile.active_team
        context['title'] = 'Add lead'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = self.request.user.userprofile.active_team
        self.object.save()
        return redirect(self.get_success_url())


class LeadUpdateView(LoginRequiredMixin, UpdateView):
    model = Lead
    fields = ['name', 'email', 'description', 'priority', 'status']

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit lead'
        return context

    def get_success_url(self):
        lead = super().get_object()
        return reverse_lazy('leads:index')


class ConvertToClientView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        lead = get_object_or_404(
            Lead, created_by=request.user, pk=self.kwargs.get('pk'))
        team = request.user.userprofile.active_team
        clients = Client.objects.filter(created_by=request.user)

        if len(clients) < team.plan.max_clients:

            client = Client.objects.create(
                name=lead.name,
                email=lead.email,
                description=lead.description,
                created_by=request.user,
                team=team,
            )

            # convert lead comments to client comments
            comments = lead.comments.all()
            for comment in comments:
                ClientComment.objects.create(
                    team=comment.team,
                    client=client,
                    content=comment.content,
                    created_by=comment.created_by,
                )

            # delete the lead after converting it to a client
            lead.converted_to_client = True
            lead.delete()

            messages.success(request, 'The lead was converted to a client')

        else:
            messages.error(
                request, 'Your team has reached maximum number of clients. Your owner must upgrade your plan!')

        return redirect('leads:index')


class AddFileView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            file = form.save(commit=False)
            file.team = request.user.userprofile.active_team
            file.created_by = request.user
            file.lead_id = pk
            file.save()

        return redirect('leads:detail', pk=pk)


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.team = request.user.userprofile.active_team
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)

lead/templates/lead/lead_confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}Add lead{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p class="mb-4">Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm" class="py-2 px-4 rounded-xl text-white bg-teal-500">
    </form>
{% endblock %}

lead/templates/lead/lead_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

    {% if lead.description %}
        <p class="font-semibold">name</p>
        <p class="mb-2">{{ lead.description }}</p>
    {% endif %}

    <p class="font-semibold">Priority</p>
    <p class="mb-2">{{ lead.get_priority_display }}</p>

    <p class="font-semibold">Status</p>
    <p class="mb-2">{{ lead.get_status_display }}</p>

    <p class="font-semibold">Created at</p>
    <p class="mb-2">{{ lead.created_at }}</p>

    <p class="font-semibold">Modified at</p>
    <p class="mb-6">{{ lead.modified_at }}</p>

    <hr class="my-4">
        <a href="{% url 'leads:convert' lead.id %}" class="py-2 px-4 rounded-xl text-white bg-teal-500">Convert to client</a>
        <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl text-white bg-blue-500">Edit</a>
        <a href="{% url 'leads:delete' lead.id %}" class="py-2 px-4 rounded-xl text-white bg-red-500">Delete</a>



    <hr class="my-4">

    <h2 class="mb-6 text-xl">Comments</h2>

    <div>
        {% for comment in lead.comments.all %}
        <div class="mb-4 bg-gray-100 px-6 py-6 rounded-xl">
            <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{comment.created_at }}</p>
            {{ comment.content }}
        </div>
        {% endfor %}
    </div>

    <form method="post" action="{% url 'leads:add_comment' lead.id %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-2 px-4 rounded-xl text-white bg-teal-500">Submit</button>
    </form>


    <hr class="my-4">

    <h2 class="mb-6 text-xl">Files</h2>

    <div>
        {% for file in lead.files.all %}
        <div class="mb-4 bg-gray-100 px-6 py-6 rounded-xl">
            <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{file.created_at }}</p>
            <a href="{{ file.file.url }}">Download</a>
        </div>
        {% endfor %}
    </div>


    <form method="post" action="{% url 'leads:add_file' lead.id %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{ fileform.as_p }}

        <button class="mt-4 py-2 px-4 rounded-xl text-white bg-teal-500">Upload</button>
    </form> 


    <hr class="my-4">

    <a href="{% url 'leads:index' %}">Back to leads</a>


{% endblock %}

lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="text-xl">{{ title }}</h1>
    {% if team.plan.max_leads > team.leads.count or title == 'Edit lead' %}
        <form method="post" action="">
            {% csrf_token %}

            {{form.as_p}}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </form>
    {% else %}
        <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
            Your team has reached maximum number of leads. Your owner must upgrade your plan!
        </div>
    {% endif %}

{% endblock %}

lead/templates/lead/lead_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <h1 class="mb-4 text-xl">Leads</h1>
    <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 text-white rounded-xl">Add lead</a>
    <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white">Export leads</a>

    {% if object_list %}
        <div class="mt-6 flex justify-between">
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        </div>
        {% for lead in object_list %}
            <div class="flex justify-between">
                <p class="py-4 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    <a href="{% url 'leads:detail' lead.id %}">{{ lead.name }}</a>
                </p>
                <p class="py-4 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                <p class="py-4 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p class="mt-6 px-2">There are no leads in the database yet.</p>
    {% endif %}
{% endblock %}